# Database connection properties` --> For Localhost	
spring.datasource.url=jdbc:mysql://localhost:3306/skillsage
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 
# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Database connection properties` --> For Deployment
#spring.datasource.url=jdbc:mysql://mysqldb:3306/spring
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 
# Hibernate properties
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.properties.hibernate.show_sql=true

# spring.datasource.hikari.maximum-pool-size=5

 
spring.jpa.generate-ddl=true
# email properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=skillssage@gmail.com
spring.mail.password=mnvj cxby jrte ksab
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
 
server.port=8001